/**
 * Maintain a marked SnFlow block inside the project .gitignore.
 * Default product policy is trackInGit=false: init/update keeps managed SnFlow
 * paths ignored so generated assets are not committed by accident.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  writeFileSync,
} from "fs";
import { randomBytes } from "crypto";
import path from "path";
import { canonicalizeCwd } from "./cwd";

export const SNFLOW_GITIGNORE_BEGIN = "# >>> snflow-managed (auto; do not edit by hand) >>>";
export const SNFLOW_GITIGNORE_END = "# <<< snflow-managed <<<";

/** Paths written by SnFlow init/update that should stay out of git by default. */
export const SNFLOW_GITIGNORE_PATTERNS = [
  ".pi/snflows/",
  ".pi/extensions/snflow/",
  ".pi/skills/snflow-dev/",
  ".pi/agents/snflow-implement.md",
  ".pi/agents/snflow-check.md",
  "scripts/snflow-task.ts",
] as const;

export type SnflowGitignoreAction = "ignored" | "tracked" | "noop" | "unchanged";

export interface SnflowGitignoreResult {
  action: SnflowGitignoreAction;
  changed: boolean;
  path: string | null;
  detail?: string;
}

function isFile(target: string): boolean {
  try {
    return existsSync(target) && statSync(target).isFile();
  } catch {
    return false;
  }
}

function buildManagedBlock(): string {
  return [
    SNFLOW_GITIGNORE_BEGIN,
    "# Generated by Snail Pi Web SnFlow setup. Remove by enabling \"Track SnFlow files in Git\".",
    ...SNFLOW_GITIGNORE_PATTERNS,
    SNFLOW_GITIGNORE_END,
  ].join("\n");
}

const BLOCK_RE = new RegExp(
  `${escapeRegExp(SNFLOW_GITIGNORE_BEGIN)}[\\s\\S]*?${escapeRegExp(SNFLOW_GITIGNORE_END)}\\n?`,
  "g",
);

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function normalizeNewlines(content: string): string {
  return content.replace(/\r\n/g, "\n");
}

function stripManagedBlock(content: string): string {
  return normalizeNewlines(content).replace(BLOCK_RE, "");
}

function ensureTrailingNewline(content: string): string {
  if (!content) return "";
  return content.endsWith("\n") ? content : `${content}\n`;
}

function atomicWrite(filePath: string, content: string): void {
  const dir = path.dirname(filePath);
  mkdirSync(dir, { recursive: true });
  const tmp = path.join(
    dir,
    `.tmp-snflow-gitignore-${process.pid}-${randomBytes(3).toString("hex")}`,
  );
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, filePath);
}

/**
 * Apply SnFlow git tracking policy for one project cwd.
 * - trackInGit=false (default): ensure managed ignore block is present
 * - trackInGit=true: remove our managed block if present
 */
export function applySnflowGitignorePolicy(
  cwd: string,
  trackInGit: boolean,
): SnflowGitignoreResult {
  const root = canonicalizeCwd(cwd);
  const gitignorePath = path.join(root, ".gitignore");

  if (trackInGit) {
    if (!isFile(gitignorePath)) {
      return { action: "noop", changed: false, path: null, detail: "no .gitignore" };
    }
    const before = readFileSync(gitignorePath, "utf8");
    const stripped = stripManagedBlock(before).replace(/\n{3,}/g, "\n\n");
    const next = ensureTrailingNewline(stripped.trimEnd() ? stripped.trimEnd() + "\n" : "");
    if (normalizeNewlines(before) === normalizeNewlines(next)) {
      return { action: "unchanged", changed: false, path: gitignorePath };
    }
    // If stripping emptied the file and it only had our block, write empty or delete?
    // Keep an empty file rather than deleting user-created .gitignore path.
    atomicWrite(gitignorePath, next);
    return {
      action: "tracked",
      changed: true,
      path: gitignorePath,
      detail: "removed SnFlow managed ignore block",
    };
  }

  // trackInGit === false → ignore managed paths
  const block = buildManagedBlock();
  if (!isFile(gitignorePath)) {
    atomicWrite(gitignorePath, `${block}\n`);
    return {
      action: "ignored",
      changed: true,
      path: gitignorePath,
      detail: "created .gitignore with SnFlow block",
    };
  }

  const before = readFileSync(gitignorePath, "utf8");
  const normalized = normalizeNewlines(before);
  const without = stripManagedBlock(normalized).replace(/\n{3,}/g, "\n\n").trimEnd();
  const next = ensureTrailingNewline(without ? `${without}\n\n${block}\n` : `${block}\n`);
  if (normalizeNewlines(before).trimEnd() === next.trimEnd()) {
    // Still rewrite if block content differs (pattern list upgraded).
    const existingMatch = normalized.match(BLOCK_RE)?.[0]?.trim();
    if (existingMatch === block) {
      return { action: "unchanged", changed: false, path: gitignorePath };
    }
  }
  atomicWrite(gitignorePath, next);
  return {
    action: "ignored",
    changed: true,
    path: gitignorePath,
    detail: "ensured SnFlow managed ignore block",
  };
}
