#!/usr/bin/env npx tsx
/**
 * Project-local SnFlow CLI wrapper for the Snail Pi Web development workflow.
 * Loads the WebUI package script in-process via dynamic import.
 *
 * Managed by SnFlow setup — do not hand-edit; re-run Update SnFlow instead.
 */

import { existsSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

// Prefer this package's own root, then honor an explicit linked-install override.
// Project-local wrappers generated by setup embed WEBUI_ROOT directly.
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const candidateRoots = [
  packageRoot,
  process.env.SNAIL_PI_WEB_ROOT,
  process.cwd(),
].filter((r): r is string => typeof r === "string" && r.length > 0);

let TARGET: string | undefined;
for (const root of candidateRoots) {
  const candidate = path.join(root, "scripts", "workflow-task.ts");
  if (existsSync(candidate)) {
    TARGET = candidate;
    break;
  }
}

if (!TARGET) {
  console.error(
    [
      "snflow-task: could not find Snail Pi Web scripts/workflow-task.ts",
      "Set SNAIL_PI_WEB_ROOT or run SnFlow Update from the WebUI Settings panel.",
    ].join("\n"),
  );
  process.exit(2);
}

(async () => {
  try {
    const { main } = await import(pathToFileURL(TARGET).href);
    await main();
  } catch (error) {
    console.error("snflow-task:", error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
})();
